# iOS Platform Bindings
# FFI bindings for iOS (UIKit)
# STATUS: Placeholder - Implementation pending

package(default_visibility = ["//visibility:public"])

# iOS bindings will be added when iOS support is implemented
# This will include UIKit-based implementations of:
# - UIButton, UITextField, UITextView
# - UIViewController, UIWindow
# - UIStackView (VStack/HStack)
# - etc.
